global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
    - 'record.geth.rules.yml'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-host:9323']
  - job_name: 'go-ethereum'
    scrape_interval: 10s
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets:
          - 'geth:6060'
        labels:
          chain: ethereum