{
 "title": "Geth Node Dashboard (Feb. 2022)2",
 "description": "A dashboard compatible with the Go Ethereum built in Prometheus metrics as of Feb 2022 (Faryar (v1.10.15))",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Transaction Rate (tx/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(txpool_known{job=\"$job\"}[1m])",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "txpool_pending{job=\"$job\"}",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "title": "Geth Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Geth CPU Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_threads{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last Received Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total System Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Geth Processor Loading",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_cpu_procload{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "rpc_requests{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Network Traffic (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(p2p_egress{job=\"$job\"}[5m])",
     "legendFormat": "Out"
    },
    {
     "expr": "rate(p2p_ingress{job=\"$job\"}[5m])",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Outgoing Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_egress{job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "Outgoing Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(p2p_egress{job=\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Activity (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{job=\"$job\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(system_disk_writebytes{job=\"$job\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Read Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk Write Activity (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_writebytes{job=\"$job\"}[1m])"
    }
   ]
  },
  {
   "title": "Chain Data Disk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{job=\"$job\"}"
    }
   ]
  }
 ]
}